CREATE OR REPLACE PACKAGE EMPLOYEES AS 

PROCEDURE ADD_DATA 
 (P_EMP_ID  IN NUMBER,
  P_EMP_NAME IN VARCHAR2,
  P_JOB      IN VARCHAR2,
  P_MGR      IN NUMBER,
  P_BOD      IN DATE,
  P_SAL      IN NUMBER,
  P_DEPTNO   IN NUMBER,
  ERROR_FLAG OUT NUMBER
 );

PROCEDURE CHANGE_DATA
 (P_EMP_ID  IN NUMBER,
  P_EMP_NAME IN VARCHAR2,
  P_JOB      IN VARCHAR2,
  P_MGR      IN NUMBER,
  P_BOD      IN DATE,
  P_SAL      IN NUMBER,
  P_DEPTNO   IN NUMBER,
  ERROR_FLAG OUT NUMBER
 );

 PROCEDURE DELETE_DATA 
 (P_EMP_ID  IN NUMBER,
  ERROR_FLAG OUT NUMBER);

 PROCEDURE DIS_DATA
 (P_EMP_ID  IN NUMBER,
  P_EMP_NAME IN VARCHAR2,
  P_JOB      IN VARCHAR2,
  P_MGR      IN NUMBER,
  P_BOD      IN DATE,
  P_SAL      IN NUMBER,
  P_DEPTNO   IN NUMBER,
  ERROR_FLAG OUT NUMBER);

 PROCEDURE DIS_BOD
(P_EMP_ID  IN NUMBER,
 ERROR_FLAG OUT NUMBER); 

END EMPLOYEES;






